### ISSUE TITLE
Github enterprise 

### ISSUE THREAD

**Issue by ananthkp92** [josephlewis42/githubbeat#20]
Hi Joseph,
I tried the pointing config to our enterprise github as mentioned in #18 . The config is as follows:
  \# The base URL of the API.
  \# Leave this blank if you want to connect to GitHub.com
  enterprise.base_url: "https://xxx.yyyyyyyy.com/"
  \# The upload URL of the API, typically this is the same as the base_url. 
  \# Leave this blank if you want to connect to GitHub.com
  enterprise.upload_url: "https://xxx.yyyyyyyy.com/"

I am getting the following error:
Exiting: Get https://api.github.com/user/repos: dial tcp 192.30.253.116:443: i/o timeout

It looks like going against github.com maybe for some api calls and proxy would not let it connect. My understanding is that it is not recognizing the configuration to monitor our enterprise github account. It is still following the default functionality to monitor  github.com repos. Please let me know whether I am using the new configuration correctly. Thanks in advance!

**Comment by josephlewis42** [comment]
Hi @ananthkp92,

Just to double-check, you're using the most recent version in the releases tab?

When you get a chance would you mind running it in verbose mode and pasting in the startup logs? One of the lines will have your configuration in it so you might want to censor the URLs, but I'd like to make sure the beat is catching the configuration correctly and following the correct startup paths. Hopefully it's just that I made a typo somewhere and the config isn't being picked up for some reason :)

Thanks!

**Comment by ananthkp92** [comment]
Hi @josephlewis42,

I am using the most recent version. It is still running againt github.com. I am getting the below output.

Exiting: GET https://api.github.com/user/repos: 401 Bad credentials []

I was using the enterprise git access_token, so that's why we are getting a 401.

Thanks

**Comment by ananthkp92** [comment]
Hi @josephlewis42,

The following is the detailed logs we are getting when running in debug mode:

2018-06-22T14:13:19.838-0400    INFO    instance/beat.go:479    Home path: [/home/xxx/githubbeat] Config path: [/home/xxx/githubbeat] Data path: [/home/xxx/githubbeat/data] Logs path: [/home/xxx/githubbeat/logs]
2018-06-22T14:13:19.838-0400    DEBUG   [beat]  instance/beat.go:506    Beat metadata path: /home/xxx/githubbeat/data/meta.json
2018-06-22T14:13:19.838-0400    INFO    instance/beat.go:486    Beat UUID: xxxxxx
2018-06-22T14:13:19.838-0400    INFO    instance/beat.go:222    Setup Beat: githubbeat; Version: 7.0.0-alpha1
2018-06-22T14:13:19.838-0400    DEBUG   [beat]  instance/beat.go:239    Initializing output plugins
2018-06-22T14:13:19.838-0400    DEBUG   [processors]    processors/processor.go:49      Processors: 
2018-06-22T14:13:19.840-0400    INFO    pipeline/module.go:76   Beat name: abc.xyz.com
2018-06-22T14:13:19.847-0400    INFO    [monitoring]    log/log.go:97   Starting metrics logging every 30s
2018-06-22T14:13:19.847-0400    INFO    instance/beat.go:312    githubbeat start running.
2018-06-22T14:13:19.847-0400    INFO    beater/githubbeat.go:45 githubbeat is running! Hit CTRL-C to stop it.
2018-06-22T14:13:19.847-0400    INFO    beater/githubbeat.go:46 configuration: {Period:1h0m0s JobTimeout:1h0m0s Repos:[ORG/ORG-repo] Orgs:[] AccessToken:xxxxxxxxxxxxxxxxxxxxxxxxxxxx StartNow:true Forks:{Enabled:false List:false Max:-1} Contributors:{Enabled:true List:true Max:-1} Branches:{Enabled:true List:false Max:-1} Languages:{Enabled:true List:true} Participation:{Enabled:true} Downloads:{Enabled:true List:false Max:-1} Issues:{Enabled:true List:true Max:-1 State:open Labels:[] Sort:created Direction:desc} Enterprise:{BaseUrl:https://ghe.com/ UploadUrl:https://ghe.com/}}
2018-06-22T14:13:19.847-0400    INFO    beater/githubbeat.go:127        Running in authentcated mode.
2018-06-22T14:13:49.851-0400    INFO    [monitoring]    log/log.go:124  Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":40,"time":{"ms":43}},"total":{"ticks":50,"time":{"ms":61},"value":50},"user":{"ticks":10,"time":{"ms":18}}},"info":{"ephemeral_id":"yyyyyyyyyyyyyyy","uptime":{"ms":30020}},"memstats":{"gc_next":4194304,"memory_alloc":1504056,"memory_total":3106144,"rss":16912384}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"cpu":{"cores":4},"load":{"1":0.1,"15":0.09,"5":0.06,"norm":{"1":0.025,"15":0.0225,"5":0.015}}}}}}
2018-06-22T14:13:49.852-0400    INFO    [monitoring]    log/log.go:132  Total non-zero metrics  {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":40,"time":{"ms":43}},"total":{"ticks":50,"time":{"ms":62},"value":50},"user":{"ticks":10,"time":{"ms":19}}},"info":{"ephemeral_id":"yyyyyyyyyyyyyyy","uptime":{"ms":30023}},"memstats":{"gc_next":4194304,"memory_alloc":1736360,"memory_total":3338448,"rss":17068032}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"cpu":{"cores":4},"load":{"1":0.1,"15":0.09,"5":0.06,"norm":{"1":0.025,"15":0.0225,"5":0.015}}}}}}
2018-06-22T14:13:49.852-0400    INFO    [monitoring]    log/log.go:133  Uptime: 30.024918663s
2018-06-22T14:13:49.852-0400    INFO    [monitoring]    log/log.go:110  Stopping metrics logging.
2018-06-22T14:13:49.852-0400    INFO    instance/beat.go:318    githubbeat stopped.
2018-06-22T14:13:49.852-0400    ERROR   instance/beat.go:678    Exiting: Get https://api.github.com/user/repos: dial tcp 192.30.253.117:443: i/o timeout
Exiting: Get https://api.github.com/user/repos: dial tcp 192.30.253.117:443: i/o timeout

Thanks

**Comment by josephlewis42** [comment]
Hi @ananthkp92,

Oh, I see what's going on! If you run in authenticated mode, the beat tries to connect to the service to verify the token _before_ it sets the custom URLs.

I changed the ordering around and I think it should be fixed. I uploaded new releases here: https://github.com/josephlewis42/githubbeat/releases/tag/v1.0.1-beta

Let me know if the work for you, unfortunately I don't have an enterprise server to test them with.

Cheers!

**Comment by ananthkp92** [comment]
Hi @josephlewis42,

Thanks for the update! Sorry I didn't get time to test the new release over the weekend. Tried with the new release but now we are getting a 406. The below is the output:

2018-06-25T11:52:38.425-0400    INFO    [monitoring]    log/log.go:132  Total non-zero metrics  {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":20,"time":{"ms":29}},"total":{"ticks":100,"time":{"ms":110},"value":100},"user":{"ticks":80,"time":{"ms":81}}},"info":{"ephemeral_id":"xxx","uptime":{"ms":249}},"memstats":{"gc_next":6553728,"memory_alloc":4111720,"memory_total":11852568,"rss":19857408}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"cpu":{"cores":4},"load":{"1":0.15,"15":0.01,"5":0.03,"norm":{"1":0.0375,"15":0.0025,"5":0.0075}}}}}}
2018-06-25T11:52:38.426-0400    INFO    [monitoring]    log/log.go:133  Uptime: 252.700363ms
2018-06-25T11:52:38.426-0400    INFO    [monitoring]    log/log.go:110  Stopping metrics logging.
2018-06-25T11:52:38.426-0400    INFO    instance/beat.go:318    githubbeat stopped.
2018-06-25T11:52:38.426-0400    ERROR   instance/beat.go:678    Exiting: GET https://ghe.com/login?return_to=https%3A%2F%2Fghe.com%2Fuser%2Frepos: 406  []
Exiting: GET https://ghe.com/login?return_to=https%3A%2F%2Fghe.com%2Fuser%2Frepos: 406  []

I am using a specific user and repo of our enterprise Git for example user123/repoabc . But in the output we are getting a 406 and I could see the GET request being generated contains our enterprise Github URL but the repo defaults to user/repos rather than user123/repoabc, we specified in the configuration yaml. I am using a personal token and I am the admin for that repo as well. Is there any specific access level to be granted for the token? Hope this makes sense.

Thanks!

**Comment by bergamoyat** [comment]
I am facing the exact problem which @ananthkp92  reported with github enterprise. Please suggest

**Comment by josephlewis42** [comment]
Hi @ananthkp92 and @bergamoyat,

I see that there's a bug filed in the `go-github` library this plugin is using. It looks like GitHub changed the enterprise API so it works more like the normal one, but that means the library might be making incorrect calls for some resources causing a content negotiation problem with the 406. I'm hoping it's just one or two of them that is causing the plugin to fail and not some deeper issue.

Can one of you try turning off all the optional data and re-running?

```yaml
  forks.enabled: false
  contributors.enabled: false
  branches.enabled: false
  languages.enabled: false
  participation.enabled: false
  downloads.enabled: false
  issues.enabled: false
```

If that doesn't work I'm sort of at a loss until I can find a way to get access to a GHE instance.

Thanks!

**Comment by ananthkp92** [comment]
Hi @josephlewis42,

 I made the above changes and ran it but we are still getting the same results. 

Thanks

**Comment by ananthkp92** [comment]
Hi @josephlewis42 ,

It there a way to print all the API calls we make against GHE while starting githubbeat? Then we would be able to provide the appropriate logs for you to analyze the issue.

Thanks

**Comment by bergamoyat** [comment]
@josephlewis42 did you get a chance to look into this ?

**Comment by josephlewis42** [comment]
Hi @bergamoyat and @ananthkp92,

Thanks for your patience, I was on holiday last week. I added a new feature to the config that will allow you to log HTTP requests and responses to stdout. `log_http_requests: true`.

I uploaded and replaced the versions of the newest binaries here so you can re-download them and give them a go: https://github.com/josephlewis42/githubbeat/releases/tag/v1.0.1-beta you should see the new option in the `githubbeat.yml` file.

Hope we can get to the bottom of this.

Cheers!
\- Joseph

**Comment by ananthkp92** [comment]
Hi @josephlewis42,

 We tried the new version, configured the yaml to monitor a repository on our enterprise github. The response we get is  *github.ErrorResponse=GET https://xxx.yyy.com/login?return_to=https%3A%2F%2Fxxx.yyy.com%2Frepos%2Fusername%2Frepo_name: 406. I could see the request adding an extra "repos" to the URL. ie,  https://xxx.yyyyy.com/repos/username/repo_name  instead of https://xxx.yyyyy.com/username/repo_name
 
Regards
Ananth

**Comment by josephlewis42** [comment]
Hi @ananthkp92,

I think that URL is correct, will you double check that your the `xxx.yyy.com` host is pointing to the API server rather than the user-facing server? The API server should be responding to things under the `/repos` directory. If I query the main GitHub API for this project, I see: 

```
2018/07/13 10:40:22 HTTP Request: GET /repos/josephlewis42/githubbeat/languages HTTP/1.1
Host: api.github.com
User-Agent: go-github
Accept: application/vnd.github.v3+json
Accept-Encoding: gzip

2018/07/13 10:40:22 Executing HTTP Request
2018/07/13 10:40:22 Got HTTP Response: HTTP/1.1 200 OK
```

Cheers!

**Comment by ananthkp92** [comment]
Hi @josephlewis42 ,

It Worked!

Thanks,
Ananth
